

export const trading_content = `# Autonomous Trading

Each agent has a wallet which it has full control over to conduct swaps (wallets are powered and secured by Privy).

The trades the agent takes undergo a lengthy research and analysis process to ensure your agent has adequate information on the assets it is buying and selling. The flow is multi-step with first the agent discovering assets and trade ideas and a watchlist of promising assets from which it actually plans trades from.

1. **Asset & Trade Discovery**
    
    There are two routes which agents find assets to trade
    
    - **General Discovery**: simple discovery from reviewing available research and news looking for hot assets and themes. It will select assets of notable hot value and plan research tasks on them which further decide if the asset should be placed on its final watchlist.
    - **Trading Strategies**: ongoing research project(s) specific to a sector or narrative which the agent maintains a sub-watchlist of projects that it continuously plans research tasks around, organizes relevant memories and content, and maintains a deep research thesis on.
2. **Watchlist Management**
    - List of assets the agent has deemed worthy enough to consider for trading
    - Each day the agent reviews these assets, the short/long-term memories, relevant news, etc and plans trades in relation to its current holdings.
    - For example, it might look at its watchlist and decide that a token there is now more promising based off its research than a token it already holds and will thus execute a swap.

![Screenshot 2025-05-18 at 4.26.52 PM.png](https://res.cloudinary.com/dgjriemfd/image/upload/v1747674567/swaps_screenshot_chebre.png)

Manual swaps are always possible too. To execute a manual swap, hover over the asset you want to trade and simply ask the agent to buy that token using a token that it holds. 

### Limitations

Currently, the agent is limited to holding and trading Solana spot assets. This is something that will change in the future as we expand to other ecosystems and products like perps.

### **Legal & Risk Disclaimer**

The following disclaimer (“**Disclaimer**”) applies to **all** use of the VELDT platform, its AI agents (“**Agents**”), ancillary tooling, and any content, recommendations, or transactions initiated or executed by an Agent. By creating, configuring, or deploying an Agent, **you acknowledge and agree** to every provision below.

1. **No Guarantee of Compliance or Outcomes**
    - Agents are autonomous, probabilistic systems. While they are provided with user‑supplied instructions, **we do not guarantee** that an Agent will understand, recall, or execute those instructions as intended.
    - Agents may behave unpredictably, generate inaccurate or inappropriate content, or deviate from stated objectives. **You accept full responsibility** for monitoring and overriding Agent activity as needed.
2. **No Investment, Trading, or Professional Advice**
    - All information, analysis, or trade execution generated by an Agent—including but not limited to portfolio allocations, market commentary, or order placement—**is for informational purposes only** and **does not constitute** investment advice, legal advice, tax advice, accounting advice, or any other professional service.
    - You should consult qualified, independent professionals before making any financial or strategic decision.
3. **Assumption of Trading & Market Risk**
    - Digital assets, derivatives, and related instruments are highly speculative and subject to extreme volatility. **Past performance is not indicative of future results.**
    - You acknowledge that **you alone bear 100 % of the risk** of loss—including complete loss of principal—arising from trades executed manually or automatically by an Agent.
    - VELDT, its affiliates, and contributors **will not be liable** for slippage, failed orders, partial fills, exchange downtime, or other market contingencies.
4. **No Fiduciary Relationship**
    - Your relationship with VELDT is **solely that of an independent user and service provider.** VELDT owes you **no fiduciary duties** (including duties of care or loyalty) and acts only as a technical facilitator.
5. **Reliance at Your Own Risk**
    - **Accuracy:** Content produced by Agents may be incomplete, outdated, or factually incorrect. Verify all data independently.
    - **Security:** You are responsible for safeguarding API keys, private keys, seed phrases, or other credentials used by your Agent.
    - **Compliance:** You are solely liable for ensuring that your Agent’s actions comply with all applicable laws, regulations, and exchange or protocol rules (e.g., KYC/AML, sanctions, securities laws).
6. **Limitation of Liability**
    - To the maximum extent permitted by law, VELDT **disclaims all warranties**, express or implied, including merchantability, fitness for a particular purpose, title, non‑infringement, and uninterrupted or error‑free operation.
    - In **no event** will VELDT, its officers, employees, agents, suppliers, or licensors be liable for **any indirect, incidental, consequential, special, exemplary, or punitive damages**, or for lost profits, lost revenue, loss of data, or business interruption, arising out of or related to Agent use—even if advised of the possibility of such damages.
    - VELDT’s aggregate liability for any claim will **not exceed the greater of** (a) USD 100 or (b) the total fees you paid to VELDT in the twelve months preceding the event giving rise to the claim.
7. **Indemnification**
    - You agree to **indemnify, defend, and hold harmless** VELDT and its affiliates from **any claims, losses, damages, liabilities, costs, and expenses** (including reasonable attorneys’ fees) arising from or related to:
        1. Your configuration, deployment, or operation of an Agent;
        2. Any violation of this Disclaimer, the platform Terms of Service, or applicable law;
        3. Any third‑party claim that your Agent’s content or actions infringed rights or caused harm.
8. **No Warranty of Availability or Data Integrity**
    - Platform uptime, data feeds, and third‑party APIs are **provided “as‑is.”** Outages, latency, or data corruption may occur without notice.
    - We reserve the right to throttle, suspend, or terminate platform access at our sole discretion.
9. **Regulatory & Jurisdictional Matters**
    - Features described herein **may not be available** in every jurisdiction. It is your responsibility to determine whether your use of an Agent is legal where you reside or operate.
    - VELDT does **not solicit** or permit Agent deployment by users or entities on any prohibited‑persons list or in any embargoed territory.
10. **Amendments & Survival**
    - We may update this Disclaimer at any time. Continued use of the platform after changes take effect constitutes acceptance.
    - Sections relating to limitation of liability, indemnification, and dispute resolution **survive** termination of platform access.
` 